#!/bin/bash

#. /usr/local/tools/dotkit/init.sh
#use -q ic-11.1.046 

set -x

./prepare
./configure \
  --prefix=`pwd`/install_bgq \
  --with-jobid-env=SLURM_JOBID \
  --disable-ld-preload \
  CC=mpixlc CFLAGS="-g -O0" || exit 1

make clean || exit 1
make || exit 1
make install || exit 1
